# Exchange API configurations
exchanges:
  binance:
    api_key: ""
    api_secret: ""
    testnet: true
  bitmex:
    api_key: ""
    api_secret: ""
    testnet: true
  deribit:
    api_key: ""
    api_secret: ""
    testnet: true

# Data collection settings
data_collection:
  liquidation:
    enabled: true
    interval: 60  # seconds
    exchanges: ["binance", "bitmex"]
  funding_rate:
    enabled: true
    interval: 3600  # seconds
    exchanges: ["binance", "bitmex", "deribit"]
  open_interest:
    enabled: true
    interval: 300  # seconds
    exchanges: ["binance", "bitmex"]
  token_launches:
    enabled: true
    interval: 3600  # seconds
    sources: ["coingecko", "binance_announcements"]
  transactions:
    enabled: true
    symbols: ["BTC/USDT", "ETH/USDT"]
    exchanges: ["binance"]

# AI model configuration
ai_module:
  model_type: "lstm"  # Options: lstm, xgboost, transformer
  training:
    batch_size: 64
    epochs: 100
    test_size: 0.2
  prediction:
    threshold: 0.75  # Confidence threshold for signals

# Execution settings
execution:
  enabled: false  # Set to true to enable live trading
  max_position_size: 1000  # in USD
  stop_loss_pct: 2.0
  take_profit_pct: 5.0
  max_open_positions: 3

# Database settings
database:
  type: "sqlite"  # Options: sqlite, postgresql, mongodb
  path: "data/trading.db"  # For sqlite
  # For other DB types:
  # host: "localhost"
  # port: 5432
  # username: ""
  # password: ""
  # database_name: "ai_trading"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/trading.log"
  rotation: "1 day"
  retention: "30 days" 